semkov/api/urls.py
from django.urls import path

from semkov.api.views import (
    ads_view,
    contact_view,
    login_view,
    logout_view,
    register_view,
)


app_name = "api"

urlpatterns = [
    path("contact/", contact_view, name="contact"),
    path("ads/", ads_view, name="ads"),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
]

semkov/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls

from semkov.search import views as search_views

urlpatterns = [
    path("django/", admin.site.urls),
    path("dashboard/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("api/", include("semkov.api.urls", namespace="api")),
    path("sitemap.xml", sitemap, name="sitemap"),
    path("", include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semkov/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls

from semkov.apps.search import views as search_views


urlpatterns = [
    path("django/", admin.site.urls),
    path("dashboard/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("api/", include("semkov.api.urls", namespace="api")),
    path("sitemap.xml", sitemap, name="sitemap"),
    path("", include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semkov/ads/models.py
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page
from wagtail.core.fields import RichTextField

from semkov.core.mixins import ImagesMixin, MenuMixin


class AdsModel(MenuMixin, ImagesMixin, Page):

    text = RichTextField()

    content_panels = (
        [FieldPanel("text")] + Page.content_panels + ImagesMixin.content_panels
    )

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Advert"
        verbose_name_plural = "Adverts"

semkov/apps/ads/models.py
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page

from semkov.apps.core.mixins import ImagesMixin, MenuMixin


class AdsModel(MenuMixin, ImagesMixin, Page):
    text = RichTextField()

    content_panels = [FieldPanel("text"), *Page.content_panels, *ImagesMixin.content_panels]

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Advert"
        verbose_name_plural = "Adverts"

semkov/apps/core/models.py
from django.db import models


class Email(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)  # noqa
    contact = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    meta = models.TextField(blank=True, null=True)  # noqa
    is_sent = models.BooleanField(blank=True, default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

semkov/apps/forum/models.py
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page

from semkov.apps.core.mixins import AttachmentsMixin, MenuMixin


class ForumModel(MenuMixin, Page):
    text = RichTextField()

    content_panels = [*Page.content_panels, FieldPanel("text")]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    class Meta:
        verbose_name = "Forum"
        verbose_name_plural = "Forums"


class ThreadModel(MenuMixin, AttachmentsMixin, Page):
    text = RichTextField()

    content_panels = [*Page.promote_panels, *AttachmentsMixin.content_panels, FieldPanel("text")]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    class Meta:
        verbose_name = "Thread"
        verbose_name_plural = "Threads"


class MessageModel(MenuMixin, AttachmentsMixin, Page):
    text = RichTextField()

    content_panels = [*Page.promote_panels, *AttachmentsMixin.content_panels, FieldPanel("text")]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"

semkov/apps/home/models.py
from django.db import models

from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page

from semkov.apps.core.mixins import MenuMixin


class HomepageModel(MenuMixin, Page):
    image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="homepage_images",
    )
    background = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="homepage_backgrounds",
    )

    content_panels = [*Page.content_panels, FieldPanel("image"), FieldPanel("background")]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    class Meta:
        verbose_name = "Homepage"
        verbose_name_plural = "Homepages"


class CategoryModel(MenuMixin, Page):
    text = RichTextField()

    content_panels = [*Page.content_panels, FieldPanel("text")]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

semkov/apps/pages/models.py
from django.db import models

from modelcluster.contrib.taggit import ClusterTaggableManager
from modelcluster.fields import ParentalKey
from taggit.models import TaggedItemBase
from wagtail.admin.panels import FieldPanel
from wagtail.models import Page

from semkov.apps.core.mixins import ArticleMixin, ImagesMixin, MenuMixin


class PageTag(TaggedItemBase):
    content_object = ParentalKey("pages.PageModel", related_name="page_tags")


class PageModel(MenuMixin, ImagesMixin, ArticleMixin, Page):
    map = models.TextField(blank=True)

    tags = ClusterTaggableManager(through="pages.PageTag", blank=True)

    content_panels = [
        FieldPanel("map"),
        FieldPanel("tags"),
        *Page.content_panels,
        *ArticleMixin.content_panels,
        *ImagesMixin.content_panels,
    ]
    promote_panels = [*Page.promote_panels, *MenuMixin.promote_panels]

    def tag_slugs(self):
        return self.tags.values_list("slug", flat=True)

    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"

semkov/apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USERNAME_FIELD = "identifier"
    REQUIRED_FIELDS = ["username", "email"]

    identifier = models.CharField(max_length=254, unique=True)
    ip_address = models.GenericIPAddressField(default="127.0.0.1", blank=True, null=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    @classmethod
    def authenticate(cls, identifier=None, password=None):
        try:
            user = cls.objects.get(identifier=identifier)
            if user.check_password(password):
                return user
        except cls.DoesNotExist:
            return None

semkov/forum/models.py
from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel

from semkov.core.mixins import AttachmentsMixin, MenuMixin


class ForumModel(MenuMixin, Page):

    text = RichTextField()

    content_panels = Page.content_panels + [FieldPanel("text")]

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Forum"
        verbose_name_plural = "Forums"


class ThreadModel(MenuMixin, AttachmentsMixin, Page):

    text = RichTextField()

    content_panels = (
        Page.content_panels + AttachmentsMixin.content_panels + [FieldPanel("text")]
    )

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Thread"
        verbose_name_plural = "Threads"


class MessageModel(MenuMixin, AttachmentsMixin, Page):

    text = RichTextField()

    content_panels = (
        Page.content_panels + AttachmentsMixin.content_panels + [FieldPanel("text")]
    )

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"

semkov/home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel

from semkov.core.mixins import MenuMixin


class HomepageModel(MenuMixin, Page):

    image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="homepage_images",
    )
    background = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="homepage_backgrounds",
    )

    content_panels = Page.content_panels + [
        ImageChooserPanel("image"),
        ImageChooserPanel("background"),
    ]

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Homepage"
        verbose_name_plural = "Homepages"


class CategoryModel(MenuMixin, Page):

    text = RichTextField()

    content_panels = Page.content_panels + [FieldPanel("text")]

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

semkov/pages/models.py
from django.db import models

from taggit.models import TaggedItemBase
from modelcluster.fields import ParentalKey
from modelcluster.contrib.taggit import ClusterTaggableManager

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.documents.edit_handlers import DocumentChooserPanel

from semkov.core.mixins import ImagesMixin, ArticleMixin, MenuMixin


class PageTag(TaggedItemBase):

    content_object = ParentalKey("pages.PageModel", related_name="page_tags")


class PageModel(MenuMixin, ImagesMixin, ArticleMixin, Page):

    document = models.ForeignKey(
        "wagtaildocs.Document",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )

    map = models.TextField(blank=True)

    tags = ClusterTaggableManager(through="pages.PageTag", blank=True)

    content_panels = (
        [DocumentChooserPanel("document"), FieldPanel("map"), FieldPanel("tags")]
        + Page.content_panels
        + ArticleMixin.content_panels
        + ImagesMixin.content_panels
    )

    promote_panels = Page.promote_panels + MenuMixin.promote_panels

    def tag_slugs(self):
        return self.tags.values_list("slug", flat=True)

    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"

semkov/apps/user/forms.py
from django import forms

from wagtail.users.forms import UserCreationForm, UserEditForm


class CustomUserEditForm(UserEditForm):
    identifier = forms.CharField(required=True)
    ip_address = forms.GenericIPAddressField()


class CustomUserCreationForm(UserCreationForm):
    identifier = forms.CharField(required=True)
    ip_address = forms.GenericIPAddressField()

semkov/api/views.py
import json
import logging

from django.contrib.auth import login, logout
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _

from wagtail.models import Page

from semkov.apps.ads.models import AdsModel
from semkov.apps.core.models import Email
from semkov.apps.core.services.recaptcha import is_valid_recaptcha_token
from semkov.apps.user.models import User


logger = logging.getLogger(__name__)


def contact_view(request):
    meta = {}
    for item in ["HTTP_ACCEPT_LANGUAGE", "HTTP_REFERER", "HTTP_USER_AGENT"]:
        meta[item] = request.META.get(item)

    if not is_valid_recaptcha_token(request.POST.get("token")):
        return JsonResponse(
            {
                "message": _("ReCaptcha token is invalid"),
            },
            status=403,
        )

    e = Email(
        name=request.POST.get("name"),
        contact=request.POST.get("contact"),
        subject=_("Submission request from Semkov app"),
        message=request.POST.get("message"),
        meta=json.dumps({"cookies": request.COOKIES, "meta": meta}),
    )
    e.save()
    return JsonResponse(
        {
            "status": 200,
            "message": _("Thanks for submission, we'll get in touch soon"),
        },
        status=200,
    )


def ads_view(request):
    if not request.user.is_authenticated:
        return JsonResponse({"status": 403, "message": _("Please login first")}, status=200)

    ads_category = Page.objects.get(slug="ads")
    ads_page = AdsModel(
        title=request.POST.get("title"),
        text=request.POST.get("text"),
        owner=request.user,
        live=False,
    )
    ads_category.add_child(instance=ads_page)
    ads_page.save()
    return JsonResponse(
        {
            "status": 200,
            "message": _("Thanks for submission, we'll post it after moderation"),
        },
        status=200,
    )


def register_view(request):
    if request.user.is_authenticated:
        return JsonResponse({"status": 400, "message": _("Already logged in")}, status=200)

    ip_address = request.META.get("REMOTE_ADDR")
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip_address = x_forwarded_for.split(",")[-1].strip()

    user = User(
        identifier=request.POST.get("identifier"),
        ip_address=ip_address,
    )
    user.set_password(request.POST.get("password"))
    user.save()

    return JsonResponse(
        {
            "status": 200,
            "message": _("Account successfully created, please wait for activation"),
        },
        status=200,
    )


def login_view(request):
    if request.user.is_authenticated:
        return JsonResponse({"status": 400, "message": _("Already logged in")}, status=200)

    user = User.authenticate(
        identifier=request.POST.get("identifier"),
        password=request.POST.get("password"),
    )
    if user is None:
        return JsonResponse(
            {
                "status": 403,
                "message": _("Can't find user with provided credentials"),
            },
            status=200,
        )

    login(request, user)
    return JsonResponse({"status": 200, "message": _("Successfully logged in")}, status=200)


def logout_view(request):
    logout(request)
    return JsonResponse({"status": 200, "message": _("Successfully logged out")}, status=200)

semkov/apps/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.contrib.search_promotions.models import Query
from wagtail.models import Page


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(
        request,
        "search/search.html",
        {"search_query": search_query, "search_results": search_results},
    )

semkov/templates/tags/document_table.html
{% load static i18n %}

<table class="document {{ classes|join:' ' }}">
  {% for item in items %}
    {% if forloop.counter == 1 %}
      <tr>
        {% for row in item.data %}
          <th>{{ row }}</th>
        {% endfor %}
        {% if item.days %}
          <th class="days">{% trans 'Days' %}</th>
        {% endif %}
      </tr>
    {% else %}
      <tr>
        {% for row in item.data %}
          <td>{{ row }}</td>
        {% endfor %}
        {% if item.days %}
          <td class="days">
            {% for key, value in item.days.items %}
              <span class="day {% if value %}active{% endif %}">
                <label>{% trans key %}</label>
              </span>
            {% endfor %}
          </td>
        {% endif %}
      </tr>
    {% endif %}
  {% endfor %}
</table>

semkov/templates/tags/header.html
{% load static i18n core_tags %}
<header>
  <div class="container">
    <div class="desktop-menu row">
      <div class="left">
        {% main_menu True %}
      </div>
      <div class="right">
        <button type="button" class="open-contact-modal outline primary">
          {% trans 'Contact Us' %}
        </button>
      </div>
    </div>
    <div class="mobile-menu row">
      <div class="left">
        <a href="/">
          <h5>{% trans 'Home' %}</h5>
        </a>
      </div>
      <div class="right">
        <button type="button" class="menu-button">
          <img id="open-mobile-menu" src="{% static 'svg/menu.svg' %}" alt="Menu">
          <img id="close-mobile-menu" src="{% static 'svg/close.svg' %}" class="hidden" alt="Close">
        </button>
        <div id="mobile-menu" class="menu">
          {% main_menu False %}
          <button class="open-contact-modal outline primary">
            {% trans 'Contact Us' %}
          </button>
        </div>
      </div>
    </div>
  </div>
</header>

<div id="contact-modal" class="modal" tabindex="-1" role="dialog">
  <div class="dialog">
    <div class="content">
      <div class="header">
        <h5 class="title">{% trans 'Feedback' %}</h5>
        <button type="button" class="close">
          <span>&times;</span>
        </button>
      </div>
      <div class="body">
        <form id="contact-form" action="{% url 'api:contact' %}" class="ajax">
          {% csrf_token %}
          <div class="group">
            <label for="name">{% trans 'Name' %}</label>
            <input id="name" name="name" type="text" placeholder="{% trans 'Enter your name' %}"
                   autocomplete="given-name">
          </div>
          <div class="group">
            <label for="contact">{% trans 'Contact' %}</label>
            <input id="contact" name="contact" type="text" aria-describedby="contactHelp"
                   placeholder="{% trans 'Enter your email or phone' %}" autocomplete="email">
            <small id="contactHelp" class="small note">
              {% trans "We'll never share your email or phone with anyone else." %}
            </small>
          </div>
          <div class="group">
            <label for="message">{% trans 'Message' %}</label>
            <textarea id="message" name="message" rows="3"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer justify-content-start">
        <button id="contact-button" type="button" class="primary">{% trans 'Send' %}</button>
        <button type="button" class="close outline secondary" data-dismiss="modal">{% trans 'Close' %}</button>
      </div>
    </div>
  </div>
</div>

<div id="contact-overlay" class="overlay"></div>

semkov/templates/tags/main_menu.html
{% load i18n static %}

<ul class="main-menu">
  {% if show_index %}
    <li>
      <a href="/">
        {% trans 'Home' %}
      </a>
    </li>
  {% endif %}
  {% for item in menu_items %}
    <li>
      <a href="{{ item.url }}">
        {{ item.title }}
      </a>
      {% if item.children %}
        <ul>
          {% for child in item.children %}
            <li>
              <a href="{{ child.url }}">
                {{ child.title }}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </li>
  {% endfor %}
</ul>

semkov/templates/tags/position.html
{% load static i18n %}

<table class="document position">
  <tr>
    {% for header in headers %}
      <th class="column">{{ header }}</th>
    {% endfor %}
  </tr>
  {% for item in items %}
    <tr {% if item.is_minibus %}class="minibus"{% endif %}>
      <td class="column position">{{ item.position }}</td>
      <td class="column full-name">{{ item.full_name }}</td>
      <td class="column phone">{{ item.phone }}</td>
      <td class="column schedule">
        {% for schedule in item.schedule %}
          <div>{{ schedule }}</div>
        {% endfor %}
      </td>
      <td class="column operations">
        <ul>
          {% for operation in item.operations %}
            <li>{{ operation }}</li>
          {% endfor %}
        </ul>
      </td>
    </tr>
  {% endfor %}
</table>

semkov/templates/tags/schedule.html
{% load static i18n %}

<div class="tab-headers">
  <h3 class="tab-header active" data-id="arrival">{% translate "Arrival" %}</h3>
  <h3 class="tab-header" data-id="departure">{% translate "Departure" %}</h3>
</div>

<div id="arrival" class="tab">
  <table class="document schedule">
    <tr>
      {% for header in headers %}
        <th>{{ header }}</th>
      {% endfor %}
    </tr>
    {% for item in arrival %}
      <tr {% if not item.is_minibus %}class="bus"{% endif %}>
        <td class="time">{{ item.time }}</td>
        <td class="route-number">{{ item.number }}</td>
        <td class="route">{{ item.route }}</td>
        <td class="days">
          <div class="flex">
            {% for day in days %}
              <span class="day {% if day in item.days %}active{% endif %}"></span>
            {% endfor %}
          </div>
        </td>
      </tr>
    {% endfor %}
  </table>
</div>

<div id="departure" class="tab hidden">
  <table class="document schedule">
    <tr>
      {% for header in headers %}
        <th>{{ header }}</th>
      {% endfor %}
    </tr>
    {% for item in departure %}
      <tr {% if not item.is_minibus %}class="bus"{% endif %}>
        <td class="time">{{ item.time }}</td>
        <td class="route-number">{{ item.number }}</td>
        <td class="route">{{ item.route }}</td>
        <td class="days">
          <div class="flex">
            {% for day in days %}
              <span class="day {% if day in item.days %}active{% endif %}"></span>
            {% endfor %}
          </div>
        </td>
      </tr>
    {% endfor %}
  </table>
</div>

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/schedule.css' %}">
{% endblock %}

{% block extra_js %}
  <script type="text/javascript" src="{% static 'js/schedule.js' %}"></script>
{% endblock %}